print("==========================================================")
print("||      Selamat datang di program belajar Python!      ||")
print("==========================================================")
print("Halo user!")
print("Hari ini kita akan belajar tentang dasar-dasar Python.")
print("Kita akan mulai dengan memahami variabel dan tipe data.")
nama = input("Siapa nama kamu? ")
print(f"Halo! {nama}, senang bertemu denganmu.")
print("Sekarang, mari kita coba membuat variabel dan melakukan operasi matematika sederhana.")
angka1 = int(input("Masukkan angka pertama: "))
angka2 = int(input("Masukkan angka kedua: "))
jumlah = angka1 + angka2
print(f"Hasil penjumlahan {angka1} + {angka2} = {jumlah}")
print("Terima kasih telah belajar Python bersama kami hari ini!")
print("Sampai jumpa lagi!") 