print("==========================================================")
print("Selamat datang di program Python sederhana!")
print("==========================================================")
nama = input("Masukkan nama Anda: ")
umur = input("Masukkan umur Anda: ")
print("==========================================================")
print(f"Halo, {nama}! Anda berumur {umur} tahun.")
print("Terima kasih telah menggunakan program ini.")
print("==========================================================")
print("Program selesai. Sampai jumpa lagi!")
print("==========================================================") 