print("Hello world")
print("Selamat belajar Python!") 
print("Semangat ya!")
print("Kamu pasti bisa!")
print("Teruslah berlatih setiap hari!")
print("Jangan takut untuk mencoba hal baru!")
print("Ingat, kesalahan adalah bagian dari proses belajar.")
print("Bersabarlah dan nikmati setiap langkah perjalananmu!")
print("Selalu percaya pada dirimu sendiri!")
print("Kamu luar biasa!")